### ISSUE TITLE
Readme needs Table of Contents

### ISSUE THREAD

**Issue by mxmason** [rlynn523/shelter-dogs#19]
A ToC will allow readers to jump down through your docs or link to separate doc pages in large projects in the future. Gve the headers in your ToC `id` properties so that they can be navigated to with `#hash` routes, ex:

``` html
<ul>
<li><a href="#my-header">My header</a></li>
...
</ul>

...

<h3 id="my-header>My header</h3>
```

This is also a plus for accessibility!

**Comment by rlynn523** [comment]
added table of contents to readme
