### ISSUE TITLE
No error reporting for bad or unsuccessful requests.

### ISSUE THREAD

**Issue by mxmason** [rlynn523/shelter-dogs#21]
If either the user searches for a nonexistent breed or your connection to  the API is somehow broken, the user needs to see _something_ happen in the UI so they know your app is processing their requests even if they cannot accomplish the task they came here to do.

**Edit**: Errors are only caught if the zip code is invalid, but invalid breed names fail silently.

**Comment by rlynn523** [comment]
Updated error handling for all cases
